### ISSUE TITLE
How are httpUnsafeOrigin and httpSafeOrigin being set by the chart?

### ISSUE THREAD

**Issue by ojkastl** [cryptpad/helm#17]
The [cryptpad documentation](https://docs.cryptpad.org/en/admin_guide/installation.html#admin-cryptpad-config) that is being referenced in the `values.yaml` mentions setting both `httpUnsafeOrigin` and `httpSafeOrigin`.

The `values.yaml` however does not contain any values to set this.

Is this being taken from the ingress`s hosts? What happens if I disable the ingress?

**Comment by ojkastl** [comment]
OK, if I disable the `ingress`, the pod logs contain the following:

```["INFO","2023-10-15T08:52:10.274Z","SERVER_TELEMETRY",{"version":"5.4.0","installMethod":"helm-docker","httpUnsafeOrigin":"http://localhost:3000","httpSafeOrigin":"http://localhost:3000","consentToContact":false}]
```

So, it looks like this is being taken from the ingress only.

It might be a good idea to allow setting this even without an ingress created by the chart.

**Comment by ojkastl** [comment]
OK, looks like this can be set in the values:
https://github.com/cryptpad/helm/blob/main/charts/cryptpad/templates/configmap.yaml#L14

```
    module.exports = {
          {{- if .Values.ingress.enabled}}  
            httpUnsafeOrigin: 'https://{{ (index .Values.ingress.hosts 0).host }}',
          {{- else if .Values.config.httpUnsafeOrigin }}
            httpUnsafeOrigin: {{ .Values.config.httpUnsafeOrigin | quote }}, 
          {{- else }}
            httpUnsafeOrigin: 'http://localhost:3000',
          {{- end}}
       
          {{- if .Values.ingress.enabled }}
            httpSafeOrigin: 'https://{{ (index .Values.ingress.hosts 0).host }}',
          {{- else if .Values.config.httpSafeOrigin }}  
            httpSafeOrigin: {{ .Values.config.httpSafeOrigin | quote }}, 
          {{- else }}
            httpSafeOrigin: 'http://localhost:3000',
          {{- end}}
```

I'll prepare a PR for the values.yaml to show those values can be set.

**Comment by gsautner** [comment]
Indeed, will be great your contrib to these instructions and improvement.
